name: Deploy Astro site to Pages

on:
  # main 브랜치에 푸시될 때 실행됩니다.
  push:
    branches: ["main"]

  # Actions 탭에서 수동으로 이 워크플로우를 실행할 수 있게 합니다.
  workflow_dispatch:

# 워크플로우가 페이지를 빌드하고 배포할 수 있도록 권한을 설정합니다.
permissions:
  contents: read
  pages: write
  id-token: write

# 동시 배포를 하나만 허용하고, 진행 중인 실행은 취소합니다.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Bun 설치 (공식 action 사용)
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      # 의존성 설치 (bun install 사용)
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      # Astro 사이트 빌드 (bun run build 사용)
      - name: Build with Astro
        run: bun run build
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # dist 폴더에서 아티팩트를 업로드합니다.
          path: ./dist
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4